services:
    aimger:
        env_file: .env
        image: ${IMAGE_NAME}
        container_name: ${CONTAINER_NAME}
        build:
            context: .
            dockerfile: docker/debian.dockerfile
            args:
                - TIME_ZONE=${TIME_ZONE}
                - USER_NAME=${CONTAINER_USER_NAME}
                - USER_ID=${CONTAINER_USER_ID}
                - GROUP_ID=${CONTAINER_GROUP_ID}
        ports:
            - mode: ingress
              host_ip: ${HOST_IP} # 0.0.0.0 если надо открыть порт для всех, 127.0.0.1 если только для host машины
              protocol: tcp
              target: ${CONTAINER_PORT}
              published: ${HOST_PORT}
        extra_hosts:
            -   ${EXTRA_HOST_0:-host_0:127.0.0.1}
            -   ${EXTRA_HOST_1:-host_1:127.0.0.1}
            -   ${EXTRA_HOST_2:-host_2:127.0.0.1}
            -   ${EXTRA_HOST_3:-host_3:127.0.0.1}
            -   ${EXTRA_HOST_4:-host_4:127.0.0.1}
            -   ${EXTRA_HOST_5:-host_5:127.0.0.1}
            -   ${EXTRA_HOST_6:-host_6:127.0.0.1}
            -   ${EXTRA_HOST_7:-host_7:127.0.0.1}
            -   ${EXTRA_HOST_8:-host_8:127.0.0.1}
            -   ${EXTRA_HOST_9:-host_9:127.0.0.1}
        deploy:
            resources:
                limits:
                    cpus: ${DOCKER_LIMIT_CPUS}
                    memory: ${DOCKER_LIMIT_MEMORY}
                reservations:
                    cpus: ${DOCKER_RESERVATION_CPUS}
                    memory: ${DOCKER_RESERVATION_MEMORY}
            restart_policy:
                condition: any
        restart: unless-stopped
